# Generated by Django 2.0.2 on 2018-03-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('date_purchased', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Car', 'Car'), ('Entertainment', 'Entertainment')], max_length=100)),
                ('subcategroy', models.CharField(choices=[('Eat Out', 'Eat Out'), ('Grocery', 'Grocery'), ('Gas', 'Gas'), ('Car Maintenance', 'Car Maintenance'), ('Party', 'Party'), ('One-Timer', 'One-Timer'), ('Gift', 'Gift')], max_length=100)),
            ],
        ),
    ]
