# Generated by Django 2.0.2 on 2018-03-04 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('date_purchased', models.DateField()),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Car', 'Car'), ('Entertainment', 'Entertainment')], max_length=100)),
                ('subcategory', models.CharField(choices=[('Eat Out', 'Eat Out'), ('Grocery', 'Grocery'), ('Gas', 'Gas'), ('Car Maintenance', 'Car Maintenance'), ('Party', 'Party'), ('One-Timer', 'One-Timer'), ('Gift', 'Gift')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_limit', models.IntegerField(default=450)),
                ('car_limit', models.IntegerField(default=200)),
                ('entertainment_limit', models.IntegerField(default=550)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
