# Generated by Django 2.0.2 on 2018-03-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='subcategroy',
            new_name='subcategory',
        ),
    ]
